---
days:
  - name: St Patrick’s Day
    month: 3
    day: 17
    substitute: next_available_weekday
  - name: Easter Monday
    method: easter_day(year) + 1.day
  - name: Battle of the Boyne (Orangemen’s Day)
    month: 7
    day: 12
    substitute: next_available_weekday
  - name: Summer bank holiday
    wday: 1
    month: 8
    week: -1
