---
days:
  - name: St. Joseph's Day
    month: 3
    day: 19
  - name: Maundy Thursday
    method: easter_day(year) - 3.days
  - name: Dos de Mayo Uprising
    month: 5
    day: 2
  - name: Corpus Christi
    method: easter_day(year) + 60.days
