---
days:
  - name: St. Joseph's Day
    month: 3
    day: 19
  - name: Maundy Thursday
    method: easter_day(year) - 3.days
  - name: Galician Literature Day
    day: 17
    month: 5
  - name: Saint James
    day: 25
    month: 7
