---
days:
  - name: New Year’s Day
    day: 1
    month: 1
  - name: Easter Monday
    method: easter_day(year) + 1.day
  - name: Labour Day
    month: 5
    day: 1
  - name: Victory in Europe Day
    month: 5
    day: 8
  - name: Ascension Day
    method: easter_day(year) + 39.days
  - name: Whit Monday
    method: easter_day(year) + 50.days
    informal: true
  - name: Bastille Day
    month: 7
    day: 14
  - name: Assumption of Mary to Heaven
    month: 8
    day: 15
  - name: All Saints' Day
    month: 11
    day: 1
  - name: Armistice Day
    month: 11
    day: 11
  - name: Christmas Day
    day: 25
    month: 12
