---
substitute: true
days:
  - name: New Year’s Day
    day: 1
    month: 1
  - name: Good Friday
    method: easter_day(year) - 2.days
  - name: Early May bank holiday
    method: first_monday(year, 5)
  - name: Spring bank holiday
    method: last_monday(year, 5)
  - name: Christmas Day
    day: 25
    month: 12
  - name: Boxing Day
    day: 26
    month: 12
