---
substitute: true
days:
  - name: New Year’s Day
    day: 1
    month: 1
  - name: Good Friday
    method: easter_day(year) - 2.days
  - name: Early May bank holiday
    wday: 1
    month: 5
  - name: Spring bank holiday
    wday: 1
    month: 5
    week: -1
  - name: Christmas Day
    day: 25
    month: 12
  - name: Boxing Day
    day: 26
    month: 12
